### ISSUE TITLE
Add support to query Consul services by namespace

### ISSUE THREAD

**Issue by findkim** [hashicorp/hcat#20]
The namespace attribute is available in [health service](https://github.com/hashicorp/hcat/blob/master/dep/template_function_types.go#L62) and [catalog service](https://github.com/hashicorp/hcat/blob/master/internal/dependency/catalog_service.go#L39) objects to be consumed by templates.

Support for namespace right now I believe, relies on the namespace inherited from the ACL token used for the queries. However if the ACL token is not bound to one namespace but has permissions to access multiple namespaces, there is not a way to query using that token for services under a specific namespace with the current syntax.

```
{{ service "<TAG>.<NAME>@<DATACENTER>~<NEAR>|<FILTER>" }}
```

To extend further support for namespaces, it would be useful to query services by their namespace. It might look like adding a [namespace query option](https://github.com/hashicorp/hcat/blob/master/internal/dependency/health_service.go#L39-L50) + new template syntax to utilize the [Consul API `ns` param](https://www.consul.io/api-docs/health#ns-2)

**Comment by eikenb** [comment]
In Consul-Template this is a consul level global config option. My work there (consul-template/hcat migration) has stalled while we get CTS going so I might have missed the necessary facilities to set it in hcat.

2 Options. 
1. fix the global support that consul-template uses
2. skip global support and add per query support (and adopt consul-template to it when I get back to that)

Skipping right to 2 is probably the way to go as it looks like we need that anyways.
