### ISSUE TITLE
Indefinite hanging due to timeout error

### ISSUE THREAD

**Issue by findkim** [hashicorp/hcat#23]
Creating a new Consul client hangs indefinitely when the connection times out. A faulty network state of a machine connecting to a remote Consul cluster could result in the timeout below:

```sh
$ curl https://10.0.0.4:8500/v1/status/leader
curl: (7) Failed to connect to 10.0.0.4 port 8500: Connection timed out
```

Working with @npearce, we found that this causes Consul-Terraform-Sync to halt during startup when initializing the Consul client ([source](https://github.com/hashicorp/consul-terraform-sync/blob/286236346fa340dbcb9ec5789659210e91da2a43/controller/consul.go#L39)) -- spinning for over 30 mins. We suspect the Consul leader check ends up looping indefinitely when `net.Error.Temporary()` returns true for timeouts ([source](https://golang.org/src/net/net.go?s=17370:17406#L585) and [DNSError](https://golang.org/src/net/net.go?s=17370:17406#L633)).
 https://github.com/hashicorp/hcat/blob/5a93181f0fe6a6064a7e74a84fe8b12efd5915b8/internal/dependency/client_set.go#L130-L152

**Comment by eikenb** [comment]
Re-looking at that code... Maybe instead of continuing we just move on through to hit the time based retry system? So it's still timeout after around a minute.

Basically just changing that switch statement to something like...

```
		case net.Error:
			if !e.Temporary() {
				return e
			}
		}
```

**Comment by findkim** [comment]
That would be a reasonable solution. 👍  

On the CTS side, we'll add logging around this client creation to provide users context that this is also trying to connect to Consul (client creation and client connect) in the event it reaches the full timeout duration.

**Comment by findkim** [comment]
Typo in my PR summary and it didn't auto close the issue.
